stages:
- build
- deploy

build:
  stage: build
  script:
    - ls
    - $M2_HOME/bin/mvn clean
    - $M2_HOME/bin/mvn package -Dmaven.test.skip=true
    - ls target/
  artifacts:
    paths:
    - target/back-end.jar

