stages:
- build
- deploy

build:
  stage: build
  variables:
    DOCKER_IMAGES_NAME: "exam_back_end_image"
    DOCKER_CONTAINER_NAME: "exam_back_end_container"
  script:
    - ls
    - $M2_HOME/bin/mvn clean
    - $M2_HOME/bin/mvn package -Dmaven.test.skip=true
    - ls target/
    - docker build -t $DOCKER_IMAGES_NAME .
    - if [ $(docker ps -q --filter name=$DOCKER_CONTAINER_NAME) ]; then docker stop $DOCKER_CONTAINER_NAME;fi
    - if [ $(docker ps -aq --filter name=$DOCKER_CONTAINER_NAME) ]; then docker rm $DOCKER_CONTAINER_NAME;fi
    - docker run -d --name $DOCKER_CONTAINER_NAME $DOCKER_IMAGE_NAME -p 8088:8888
  artifacts:
    paths:
    - target/back-end.jar

